from lore.builtins.adapters.fasta import _net_charge, _net_charge_from_seq, _PKA_TOSELAND

def test_net_charge():
    test_seq = "MCTKHHACRSKSLTQPMHSHQTSCDGSPKIVAIRAAGVSASCDGDSCCTSDGGGGATLEEDPERRHEPRSSHYQQSWYIAGMDCPSCAQKIEKAVKQLGDVTQVQVMFATQKLVVGFNQPSTAPLIEQAVRDSGFSLNPAASSAATPSQSKPPLWQSENARIIGIAALMAIGALVNSSEMSRWIYTLTCLLGLFPILQQAWRLAKSGSPFSIETLMSVAAIGALYLGETLEAAMVLLLFLIGERLEAYAASRARTGVQALMALVPETAIRIEHGERVTVPAAQLQPGDVIEVAPGGRLPADGRLLAAASLDNSALTGESLPVELTAGERVSAGCVIVDKVVQIEITSKQGENAIDRILHMIEEAESRKAPLERFLDKFSRWYTPLMMLVALAVIVVPPLAFGADWQTWIYRGLALLLIACPCALVISTPAAITSGLAAAARRGALIKGGAALEQLGKIETIAFDKTGTLTEGKPQVTDLIPLQGWDSATLLARAAAIEMGSHHPLATSLVAKAQAEQLTIPQAQERTALVGRGISGQIDGVQYRLLAPNRVETKLPDVVKQHVEMLEAESKTVVVMLASDAVVGVIAWQDTLRSDARQAVAALHQLGINALMLTGDNERSAAAMSQQLNMDFRAGLLPQDKVGYIQQLAQHQRVAMVGDGINDAPAMKEASIGIAMGGGTDVALETADAALTHNRLIELPGMIELSRATLAIIRQNVVLALGLKAVFLVTSLLGITGLWMAVLADSGATALVTLNALRLLKFRSSTSE"
    charged_aa_counts = {'D': 0, 'E': 0, 'C': 0, 'Y': 0, 'H': 0, 'K': 0, 'R': 0}
    for aa in test_seq:
        if aa in charged_aa_counts: 
            charged_aa_counts[aa] += 1
    aa_vec = list(charged_aa_counts.values())
    
    assert abs(_net_charge(aa_vec, 7.0, _PKA_TOSELAND) - _net_charge_from_seq(test_seq, 7.0, _PKA_TOSELAND)) < 0.0001