"""
Artifact data model definitions. An Artifact is a discrete unit of data managed 
by LoRe. It has various metadata and is tied to a physical file.
"""

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
import posixpath
from pydantic import BaseModel, Field, computed_field
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from lore.core.adapters import BaseAdapter
    from lore.core.tasks import TaskDefinition


class BaseArtifact(BaseModel, ABC):
    """
    Base class for all Artifacts (both realized and future).
    """
    id: str
    data_type: str = "unknown"  # LoRe data type tags (e.g. "fasta", "json_report")
    name: str | None = None

    @property
    @abstractmethod
    def is_resolved(self) -> bool:
        pass

    @property
    @abstractmethod
    def ui_name(self) -> str:
        """Returns a UI-friendly short name"""
        pass

    @property
    @abstractmethod
    def extension(self) -> str:
        """File extension for adapter format matching"""
        pass

    # --- Pipeline Logic ---

    def get_adapters(self) -> list["BaseAdapter"]:
        """
        Convenience accessor for valid Adapters for this Artifact.
        """
        from lore.core.adapters import adapter_registry
        return adapter_registry.get_adapters_by_type(self.data_type, self.extension)

    def resolvable_types(self) -> set[str]:
        """
        Determine semantic types this Artifact can satisfy.
        Includes: its base type, explicit adapter types, dynamic schema types.
        """
        from lore.core.adapters import TableAdapter

        resolvable = {self.data_type}

        for adapter in self.get_adapters():
            resolvable.update(adapter.provided_types)

            # Note: If adapter.schema is dynamically generated by reading a file, 
            # this will safely skip for FutureArtifacts assuming they aren't instantiated 
            # with file paths, or you can rely on static schema definitions on the Adapter.
            if isinstance(adapter, TableAdapter) and getattr(adapter, 'schema', None):
                resolvable.update(adapter.schema.keys())

        return resolvable

    def get_push_tasks(self) -> list["TaskDefinition"]:
        """
        Return Tasks that can accept this artifact as a valid input.
        """
        from lore.core.tasks import task_registry
        return task_registry.compatible_tasks(self.resolvable_types())


class Artifact(BaseArtifact):
    """
    A concrete, discrete unit of data managed by LoRē.
    """
    path: str  # relative to Session dir for portability
    size_bytes: int
    hash: str

    # Lineage
    created_by_task_id: str | None = None
    parent_artifact_ids: list[str] = Field(default_factory=list)

    # Metadata
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def is_resolved(self) -> bool:
        return True

    @property
    def is_remote(self) -> bool:
        """Returns True if the path is an external URI rather than a local file."""
        return self.path.startswith(("http://", "https://", "s3://", "gs://", "ftp://"))

    @property
    def filename(self) -> str:
        """Final path component e.g. `genome_report.json`"""
        if self.is_remote:
            from urllib.parse import urlparse
            clean_path = urlparse(self.path).path
            return posixpath.basename(clean_path)
        return Path(self.path).name

    @property
    def extension(self) -> str:
        """Just the file extension without the dot e.g. `json`"""
        if self.is_remote:
            name = self.filename
            return name.split(".")[-1] if "." in name else ""
        return Path(self.path).suffix.lstrip(".")

    # --- UI ---

    @computed_field
    def display_size(self) -> str:
        """Returns human-readable size."""
        b = self.size_bytes
        if b < 1024:
            return f"{b} B"
        elif b < 1024 * 1024:
            return f"{b / 1024:.1f} kB"
        elif b < 1024 * 1024 * 1024:
            return f"{b / (1024 * 1024):.1f} MB"
        else:
            return f"{b / (1024 * 1024 * 1024):.2f} GB"

    @property
    def ui_name(self) -> str:
        """Returns a UI-friendly short name"""
        if self.name:
            return self.name if len(self.name) <= 20 else str(self.name)[:17] + "..."
        else:
            return f"<Artifact ID: {self.id[:4]}...>"


class FutureArtifact(BaseArtifact):
    """
    A promise of an Artifact that will eventually be generated by a Task. Used 
    for forward references during Task planning.
    """
    source_step_id: str = Field(description="Task ID that will produce this.")
    source_output_key: str = Field(description="Output key from the Task that will produce this.")

    @property
    def is_resolved(self) -> bool:
        return False

    @property
    def extension(self) -> str:
        """
        A future artifact has no physical file yet.
        Returning the wildcard '*' allows the AdapterRegistry to bypass 
        the physical format check and match solely on semantic `data_type`. Mis-
        configuration will fail loudly during Task execution.
        """
        return "*"

    @property
    def ui_name(self) -> str:
        """Returns a UI-friendly short name"""
        if self.name:
            return f"(Future) {self.name}"
        return f"<Future Artifact from {self.source_step_id}:{self.source_output_key}>"
